name = "SingleDealerAssortment"
uuid = "54b42929-2009-42cd-ac67-b6adad20a794"
authors = ["NicolasCorvol <nicolas.corvol@eleves.enpc.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
