name = "SingleDealerAssortment"
uuid = "54b42929-2009-42cd-ac67-b6adad20a794"
version = "1.0.0-DEV"
authors = ["NicolasCorvol <nicolas.corvol@eleves.enpc.fr> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
InferOpt = "4846b161-c94e-4150-8dac-c7ae193c601f"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"

[compat]
CSV = "0.10.15"
Combinatorics = "1.0.3"
DataFrames = "1.8.1"
DataStructures = "0.19.3"
Distributions = "0.25.122"
DocStringExtensions = "0.9.5"
Flux = "0.16.5"
Gurobi = "1.8.0"
HiGHS = "1.20.1"
InferOpt = "0.6.1"
IterTools = "1.10.0"
JLD2 = "0.6.3"
JSON = "1.3.0"
JuMP = "1.29.3"
NNlib = "0.9.31"
OhMyThreads = "0.8.3"
Plots = "1.41.1"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Revise = "3.12.2"
Statistics = "1.11.1"
StatsPlots = "0.15.8"
TensorBoardLogger = "0.1.26"
julia = "1.12.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
